### PR TITLE
coverage: Switch to ocaml-travis-coveralls

### PR DESCRIPTION
**Pull request by simonjbeaumont**
Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
Hopefully #6 and probably supersedes #1.

**Comment by simonjbeaumont** [comment]
Teething issues to be solved when not overriding some options. I'll use this pull-req as a playground if that's OK.

**Comment by djs55** [comment]
Sounds good!

**Comment by simonjbeaumont** [comment]
OK, I think the niggles are all solved now but it's not been enabled?

https://coveralls.io/github/djs55 doesn't list it and Travis gets as far as uploading and gets an error:
```
$TRAVIS set; running ocveralls and sending to coveralls.io...
Fatal error: exception Failure("'curl -sLf -F json_file=@- https://coveralls.io/api/v1/jobs' exited with 22.")
~/build/djs55/ocaml-9p
The command "bash -ex .travis-opam.sh && bash -ex travis-coveralls.sh" exited with 2.
```

Looks like this seems to agree:
```sh
$ KEEP=1 bash travis-coveralls.sh >/dev/null 2>&1
$ cd .coverage/
$ export TRAVIS=1
$ export TRAVIS_JOB_ID=1
$ ocveralls --prefix _build bisect0001.out --output dump.json
$ curl -sL -F json_file=@- https://coveralls.io/api/v1/jobs < dump.json                                                                   
{"message":"Couldn't find a repository matching this job.","error":true}
```

@djs55 I think if you enable it on coveralls.io (it took a few attempts when I tried on my repo cos coveralls is a bit flakey) and then hit rebuild on the Travis job we can see if we're there.

**Comment by djs55** [comment]
Oops, just added it on coveralls, will resubmit Travis job

**Comment by simonjbeaumont** [comment]
Behold: your coverage is 49.88%—https://coveralls.io/builds/3935290.

If you need to disable any code there's support for that.

**Comment by djs55** [comment]
But 100% of infix.ml!

Thanks!

**Pull request merged**
